repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
  - repo: local
    hooks:
      - id: check-no-sqlite
        name: Check for SQLite usage (PostgreSQL-only)
        entry: python scripts/check_no_sqlite.py
        language: system
        files: \.(py)$
        exclude: |
          (?x)(
            ^scripts/check_no_sqlite\.py$|
            ^__pycache__/|
            ^\.git/|
            ^node_modules/|
            ^_reports/|
            ^artifacts/
          )
