rules:
  # Ignore false positive Flask XSS warnings for safe URL building functions
  - id: python.flask.security.audit.directly-returned-format-string.directly-returned-format-string
    paths:
      include:
        - app/integrations/google/routes.py
        - app/url_helpers.py
        - app/security.py
    pattern: |
      return f"$URL"

# Alternative approach: disable the rule entirely for these safe functions
disable:
  - python.flask.security.audit.directly-returned-format-string.directly-returned-format-string
