[tool.ruff]
target-version = "py311"
line-length = 100
extend-exclude = [
  "data/**",
  "scripts/**",
  "node_modules/**",
  "venv/**",
  ".venv/**",
]

# Keep rule surface focused on correctness + clarity
select = ["E","F","I","UP","B","N"]
# Explicitly ensure pyflakes rule for rebinding imported names is enabled
# (e.g. shadowing `Request`, `Response`, `status`) - pyflakes emits F823
extend-select = ["F823"]
ignore = ["E501"]
