[tool.ruff]
target-version = "py311"
line-length = 100
extend-exclude = [
  "data/**",
  "scripts/**",
  "node_modules/**",
  "venv/**",
  ".venv/**",
]

# Keep rule surface focused on correctness + clarity
select = ["E","F","I","UP","B","N"]
ignore = ["E501"]
