name: Contract Check
on:
  pull_request:
    paths:
      - "app/**"
      - "tests/contract/**"
      - "tests/api/**"
      - "tests/routing/**"
      - "pyproject.toml"

jobs:
  contract-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip wheel
          pip install -e .[test]
      - name: Pytest (contracts only)
        env:
          ENV: test
          TEST_OFFLINE: "1"
          STARTUP_VENDOR_PINGS: "0"
          VECTOR_STORE_KIND: memory
        run: |
          . .venv/bin/activate
          pytest tests/contract tests/api/contract tests/routing \
            -m "contract or not contract" \
            --maxfail=1 -q \
            --junitxml=reports/junit-contracts.xml
      - name: Upload JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-contracts
          path: reports/junit-contracts.xml
