name: Contract Check
on: [push, pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install fastapi starlette uvicorn pytest
      - name: Validate contract artifact present
        run: |
          test -f docs/auth_contract.md
      - name: Run unit tests
        env:
          CSRF_ENABLED: '1'
        run: pytest -q
